### ISSUE TITLE
Purchase Invoice

### ISSUE THREAD

**Issue by NewtonTwl** [odakerp2024/odakerp_finance_frontend#25]
The design of the Purchase invoice (Admin) screen and the specified modifications need to be processed

**Comment by SrinivasanTwilight** [comment]
1. The provision type and provision No should reflect after selecting the Against provision only until these two fields are not displaying. | Open
-- | --
2. Required to show the vendor branch name rather than the branch code. | Completed in local
3. If the vendor has credits, the invoice date or credit days (invoice date + credit date "get from vendor master for credit days") should be used as the due date. | Open
4. The selected order type wants to be retrieved into the account details based on the purchase order and internal order details. | Open
5. There should be three decimal point options for the Rate and   Quantity. | Open
6. The screen must be aligned (space is needed for the account,   rate, and amount). | Open
7. Take out the currency name from the currency field.(Only currency code should show) | Completed in local
8. The error message "Please Enter GST group"   appears when we try to select the GST group as "0%". | Completed in local
9. When saving or finalizing the invoice, the bank details and exchange rate should be Mandatory. | Completed in local
10. The tax calculation was incorrect. that is, even though we added two accounts with two different tax codes, you summed both taxes and displayed the total invoice amount. (You must calculate the tax percentage   row-by-row rather than adding taxes such as 5% + 18% = 23%.) "Need to   calculate 1000*5/100 and 2000*18/100" ) | Open
11. The purchase invoice could not be saved because the conversion failed to convert the variable. | Completed in local
12. Only the final provision should be fetched to the purchase invoice, as indicated in the provision draft status too. | Completed in local
13. The 
14. particulars of the selected provision charge are not displayed. | Open

**Comment by SrinivasanTwilight** [comment]
Newly Added  Scenarios:

1. Vendor-based GST category should not calculate GST - Overseas or SEZ
2. TDS 
 - If YES, validate and If TDS is selected should calculate  in Grid
 - If No or LDC, not validate and If TDS select should not calculate in Grid
 - IF LDC should calculate the LDC Rate with all account details
 
3. Order type based grid items should show

**Comment by SrinivasanTwilight** [comment]
1. Alignment issues are there (rate, account)-Account Tab
2. Ex. Rate Not allowed are decimal points.
3. Unable to edit the charges retrieved from purchase order.
4. After saving, All the records are disappeared.(Purchase order number and Charge details)
5. After saving, The uploaded file are disappeared.
6. After saving, Vendor branch was changed to ID rather than name
